/**
 * Generates hippocampus-sync.config.md — the companion config file
 * that the synthesis skill reads at Step 0.
 *
 * This file lives in the agent's workspace root and contains:
 * - Domain framing
 * - Source table with extraction guidance
 * - Output sections with descriptions
 * - Target size range
 * - Rolling window days
 * - Writing quality guidance
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { AgentConfig, HippocampusSource } from "../config.js";
import { KNOWN_OUTPUT_SECTIONS } from "../config.js";

/**
 * Generate and write the companion config file for an agent.
 */
export function generateCompanionConfig(
  workspaceDir: string,
  agentId: string,
  agentRole: string,
  config: AgentConfig,
): { path: string; content: string } {
  const content = buildConfigContent(agentId, agentRole, config);
  const configPath = join(workspaceDir, "hippocampus-sync.config.md");
  writeFileSync(configPath, content, "utf-8");
  return { path: configPath, content };
}

function buildConfigContent(
  agentId: string,
  agentRole: string,
  config: AgentConfig,
): string {
  const lines: string[] = [];

  lines.push(`# Hippocampus Sync Configuration — ${agentId}`);
  lines.push("");
  lines.push(`> Auto-generated by the Hippocampus plugin setup wizard.`);
  lines.push(`> Edit this file to customise your synthesis. The hippocampus-sync skill reads it at Step 0.`);
  lines.push("");

  // Domain framing
  lines.push("## Domain Framing");
  lines.push("");
  if (config.domainFraming) {
    lines.push(config.domainFraming);
  } else {
    lines.push(`This is a general-purpose working memory synthesis for **${agentRole}**. The primary question is: "What is this agent focused on, what's in flight, what's blocked, and what decisions are pending?"`);
  }
  lines.push("");

  // Settings
  lines.push("## Settings");
  lines.push("");
  lines.push(`- **Rolling window:** ${config.rollingWindowDays} days`);
  lines.push(`- **Target size:** ${config.targetSizeChars.min}–${config.targetSizeChars.max} characters`);
  lines.push("");

  // Source table
  lines.push("## Source Data");
  lines.push("");
  lines.push("Read these sources in the order listed. For windowed sources, only read files within the rolling window.");
  lines.push("");
  lines.push("| # | Source | Path | Windowed | What to Extract |");
  lines.push("|---|--------|------|----------|-----------------|");
  config.sources.forEach((source, i) => {
    const windowed = source.windowed !== false ? "Yes" : "No";
    const extract = source.whatToExtract ?? "All relevant content";
    const label = source.label ?? source.id;
    lines.push(`| ${i + 1} | ${label} | \`${source.path}\` | ${windowed} | ${extract} |`);
  });
  lines.push("");

  // Output sections
  lines.push("## Output Sections");
  lines.push("");
  lines.push("Include these sections in HIPPOCAMPUS.md, in this order:");
  lines.push("");
  for (const section of config.outputSections) {
    const description = KNOWN_OUTPUT_SECTIONS[section] ?? "Custom section — follow your domain framing to determine content";
    lines.push(`1. **${formatSectionName(section)}** — ${description}`);
  }
  lines.push("");

  // Custom sections guidance
  const customSections = config.outputSections.filter((s) => !KNOWN_OUTPUT_SECTIONS[s]);
  if (customSections.length > 0) {
    lines.push("### Custom Section Guidance");
    lines.push("");
    lines.push("The following sections are domain-specific. Use your domain framing to determine what belongs in each:");
    lines.push("");
    for (const section of customSections) {
      lines.push(`- **${formatSectionName(section)}:** Populate based on source data relevant to this domain aspect.`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function formatSectionName(section: string): string {
  return section
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
